# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build App"
  lane :beta do
    setup_ci

    match(
      type: "development", 
      readonly: true
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "3BT7A38RRX"
    )

    build_app(
      scheme: "SwiftDemos",
      configuration: "Debug",
      export_method: "development",
      export_team_id: "3BT7A38RRX",
      clean: true
    )
  end
end
